name: Terraform Apply Workflow

on:
  push:
    branches: [ "ping-vms" ]
  workflow_dispatch:
# 
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_ADMIN_PASSWORD: ${{ secrets.TF_VAR_ADMIN_PASSWORD }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
      - name: Terraform Destroy (Auto Cleanup)
        if: always()
        run: terraform destroy -auto-approve